version: '1'
services:
  sb3-java17-mvcapp:
    container_name: sb3-java17-mvcapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    image: sb3-java17-mvcapp:latest
    ports:
      - 8080:8080
